# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: FristJob
      steps:
      - bash: echo Build FirstJob
    - job: SecondJob
      steps:
      - bash: echo Build SecondJob

  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - deployment: DevDeployment
        pool:
          vmImage: ubuntu-latest
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
              - bash: echo DevDeployJob
      - job: DevDeploySecondJob
        steps:
          - bash: echo DevDeploySecondJob

  - stage: QADeploy
    dependsOn: DevDeploy
    jobs:
    - deployment: QADeployment
      pool:
        vmImage: ubuntu-latest
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo QADeployJob
    - job: SecondJob
      steps:
      - bash: echo QADeploy SecondJob

  - stage: PreProdDeploy
    dependsOn:
    - DevDeploy
    - QADeploy
    jobs:
    - deployment: PreProdDeployment
      pool:
        vmImage: ubuntu-latest
      environment: Pre-Prod
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo PreProdDeployJob
    - job: SecondJob
      steps:
      - bash: echo PreProdDeploy SecondJob

  - stage: ProdDeploy
    dependsOn:
    - DevDeploy
    - QADeploy
    - PreProdDeploy
    jobs:
    - deployment: ProdDeployment
      pool:
        vmImage: ubuntu-latest
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo ProdDeployJob
    - job: SecondJob
      steps:
      - bash: echo ProdDeploy SecondJob  